
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Image image42;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Image image40;
	
	private global::Gtk.DrawingArea lcdDrawingarea;
	
	private global::Gtk.Image image41;
	
	private global::Gtk.Image image39;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Image image20;
	
	private global::Gtk.EventBox escEventbox;
	
	private global::Gtk.Image escImage;
	
	private global::Gtk.Image image18;
	
	private global::Gtk.Image image22;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Image image21;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.EventBox eventbox4;
	
	private global::Gtk.EventBox upEventbox;
	
	private global::Gtk.Image upImage;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Image image24;
	
	private global::Gtk.Image image25;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Image image26;
	
	private global::Gtk.EventBox leftEventbox;
	
	private global::Gtk.Image leftImage;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.EventBox eventbox10;
	
	private global::Gtk.Image upImageSmall1;
	
	private global::Gtk.EventBox eventbox11;
	
	private global::Gtk.Image downImageSmall1;
	
	private global::Gtk.EventBox enterEventbox;
	
	private global::Gtk.Image enterImage;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.EventBox eventbox12;
	
	private global::Gtk.Image upImageSmall2;
	
	private global::Gtk.EventBox eventbox13;
	
	private global::Gtk.Image downImageSmall2;
	
	private global::Gtk.EventBox rightEventbox;
	
	private global::Gtk.Image rightImage;
	
	private global::Gtk.Image image27;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Image image35;
	
	private global::Gtk.EventBox downEventbox;
	
	private global::Gtk.Image downImage;
	
	private global::Gtk.Image image36;
	
	private global::Gtk.Image image38;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MonoBrick EV3 Simulator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Modal = true;
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		// Container child vbox1.Gtk.Box+BoxChild
		this.image42 = new global::Gtk.Image ();
		this.image42.Name = "image42";
		this.image42.Xalign = 0F;
		this.image42.Yalign = 0F;
		this.image42.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_01.png"));
		this.vbox1.Add (this.image42);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image42]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		// Container child hbox6.Gtk.Box+BoxChild
		this.image40 = new global::Gtk.Image ();
		this.image40.Name = "image40";
		this.image40.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_02.png"));
		this.hbox6.Add (this.image40);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.image40]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.lcdDrawingarea = new global::Gtk.DrawingArea ();
		this.lcdDrawingarea.Name = "lcdDrawingarea";
		this.hbox6.Add (this.lcdDrawingarea);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lcdDrawingarea]));
		w3.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.image41 = new global::Gtk.Image ();
		this.image41.Name = "image41";
		this.image41.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_04.png"));
		this.hbox6.Add (this.image41);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.image41]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.hbox6);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image39 = new global::Gtk.Image ();
		this.image39.Name = "image39";
		this.image39.Xalign = 0F;
		this.image39.Yalign = 0F;
		this.image39.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_05.png"));
		this.vbox1.Add (this.image39);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image39]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		// Container child hbox4.Gtk.Box+BoxChild
		this.image20 = new global::Gtk.Image ();
		this.image20.Name = "image20";
		this.image20.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_06.png"));
		this.hbox4.Add (this.image20);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.image20]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.escEventbox = new global::Gtk.EventBox ();
		this.escEventbox.Name = "escEventbox";
		// Container child escEventbox.Gtk.Container+ContainerChild
		this.escImage = new global::Gtk.Image ();
		this.escImage.Name = "escImage";
		this.escImage.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_07.png"));
		this.escEventbox.Add (this.escImage);
		this.hbox4.Add (this.escEventbox);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.escEventbox]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.image18 = new global::Gtk.Image ();
		this.image18.Name = "image18";
		this.image18.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_10.png"));
		this.hbox4.Add (this.image18);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.image18]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.image22 = new global::Gtk.Image ();
		this.image22.Name = "image22";
		this.image22.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_12.png"));
		this.vbox4.Add (this.image22);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.image22]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox4]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		// Container child vbox6.Gtk.Box+BoxChild
		this.image21 = new global::Gtk.Image ();
		this.image21.Name = "image21";
		this.image21.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_08.png"));
		this.vbox6.Add (this.image21);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.image21]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		// Container child hbox5.Gtk.Box+BoxChild
		this.eventbox4 = new global::Gtk.EventBox ();
		this.eventbox4.Name = "eventbox4";
		// Container child eventbox4.Gtk.Container+ContainerChild
		this.upEventbox = new global::Gtk.EventBox ();
		this.upEventbox.Name = "upEventbox";
		// Container child upEventbox.Gtk.Container+ContainerChild
		this.upImage = new global::Gtk.Image ();
		this.upImage.Name = "upImage";
		this.upImage.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_11.png"));
		this.upEventbox.Add (this.upImage);
		this.eventbox4.Add (this.upEventbox);
		this.hbox5.Add (this.eventbox4);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.eventbox4]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox6.Add (this.hbox5);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.hbox3.Add (this.vbox6);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox6]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		// Container child vbox5.Gtk.Box+BoxChild
		this.image24 = new global::Gtk.Image ();
		this.image24.Name = "image24";
		this.image24.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_09.png"));
		this.vbox5.Add (this.image24);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.image24]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.image25 = new global::Gtk.Image ();
		this.image25.Name = "image25";
		this.image25.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_13.png"));
		this.vbox5.Add (this.image25);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.image25]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.hbox3.Add (this.vbox5);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox5]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		// Container child hbox2.Gtk.Box+BoxChild
		this.image26 = new global::Gtk.Image ();
		this.image26.Name = "image26";
		this.image26.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_14.png"));
		this.hbox2.Add (this.image26);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image26]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.leftEventbox = new global::Gtk.EventBox ();
		this.leftEventbox.Name = "leftEventbox";
		// Container child leftEventbox.Gtk.Container+ContainerChild
		this.leftImage = new global::Gtk.Image ();
		this.leftImage.Name = "leftImage";
		this.leftImage.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_15.png"));
		this.leftEventbox.Add (this.leftImage);
		this.hbox2.Add (this.leftEventbox);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.leftEventbox]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		// Container child vbox2.Gtk.Box+BoxChild
		this.eventbox10 = new global::Gtk.EventBox ();
		this.eventbox10.Name = "eventbox10";
		// Container child eventbox10.Gtk.Container+ContainerChild
		this.upImageSmall1 = new global::Gtk.Image ();
		this.upImageSmall1.Name = "upImageSmall1";
		this.upImageSmall1.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_16.png"));
		this.eventbox10.Add (this.upImageSmall1);
		this.vbox2.Add (this.eventbox10);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.eventbox10]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.eventbox11 = new global::Gtk.EventBox ();
		this.eventbox11.Name = "eventbox11";
		// Container child eventbox11.Gtk.Container+ContainerChild
		this.downImageSmall1 = new global::Gtk.Image ();
		this.downImageSmall1.Name = "downImageSmall1";
		this.downImageSmall1.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_21.png"));
		this.eventbox11.Add (this.downImageSmall1);
		this.vbox2.Add (this.eventbox11);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.eventbox11]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.hbox2.Add (this.vbox2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
		w31.Position = 2;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.enterEventbox = new global::Gtk.EventBox ();
		this.enterEventbox.Name = "enterEventbox";
		// Container child enterEventbox.Gtk.Container+ContainerChild
		this.enterImage = new global::Gtk.Image ();
		this.enterImage.Name = "enterImage";
		this.enterImage.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_17.png"));
		this.enterEventbox.Add (this.enterImage);
		this.hbox2.Add (this.enterEventbox);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.enterEventbox]));
		w33.Position = 3;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		// Container child vbox3.Gtk.Box+BoxChild
		this.eventbox12 = new global::Gtk.EventBox ();
		this.eventbox12.Name = "eventbox12";
		// Container child eventbox12.Gtk.Container+ContainerChild
		this.upImageSmall2 = new global::Gtk.Image ();
		this.upImageSmall2.Name = "upImageSmall2";
		this.upImageSmall2.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_18.png"));
		this.eventbox12.Add (this.upImageSmall2);
		this.vbox3.Add (this.eventbox12);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox12]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.eventbox13 = new global::Gtk.EventBox ();
		this.eventbox13.Name = "eventbox13";
		// Container child eventbox13.Gtk.Container+ContainerChild
		this.downImageSmall2 = new global::Gtk.Image ();
		this.downImageSmall2.Name = "downImageSmall2";
		this.downImageSmall2.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_22.png"));
		this.eventbox13.Add (this.downImageSmall2);
		this.vbox3.Add (this.eventbox13);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.eventbox13]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		this.hbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
		w38.Position = 4;
		w38.Expand = false;
		w38.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.rightEventbox = new global::Gtk.EventBox ();
		this.rightEventbox.Name = "rightEventbox";
		// Container child rightEventbox.Gtk.Container+ContainerChild
		this.rightImage = new global::Gtk.Image ();
		this.rightImage.Name = "rightImage";
		this.rightImage.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_19.png"));
		this.rightEventbox.Add (this.rightImage);
		this.hbox2.Add (this.rightEventbox);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.rightEventbox]));
		w40.Position = 5;
		w40.Expand = false;
		w40.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.image27 = new global::Gtk.Image ();
		this.image27.Name = "image27";
		this.image27.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_20.png"));
		this.hbox2.Add (this.image27);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image27]));
		w41.Position = 6;
		w41.Expand = false;
		w41.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w42.Position = 4;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		// Container child hbox1.Gtk.Box+BoxChild
		this.image35 = new global::Gtk.Image ();
		this.image35.Name = "image35";
		this.image35.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_23.png"));
		this.hbox1.Add (this.image35);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image35]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.downEventbox = new global::Gtk.EventBox ();
		this.downEventbox.Name = "downEventbox";
		// Container child downEventbox.Gtk.Container+ContainerChild
		this.downImage = new global::Gtk.Image ();
		this.downImage.Name = "downImage";
		this.downImage.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_24.png"));
		this.downEventbox.Add (this.downImage);
		this.hbox1.Add (this.downEventbox);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.downEventbox]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image36 = new global::Gtk.Image ();
		this.image36.Name = "image36";
		this.image36.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_25.png"));
		this.hbox1.Add (this.image36);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image36]));
		w46.Position = 2;
		w46.Expand = false;
		w46.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w47.Position = 5;
		w47.Expand = false;
		w47.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image38 = new global::Gtk.Image ();
		this.image38.Name = "image38";
		this.image38.Xalign = 0F;
		this.image38.Yalign = 0F;
		this.image38.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Images/EV3-multibrick_26.png"));
		this.vbox1.Add (this.image38);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image38]));
		w48.Position = 6;
		w48.Expand = false;
		w48.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 338;
		this.DefaultHeight = 465;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.escEventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEscEventboxButtonPressEvent);
		this.escEventbox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnEscEventboxButtonReleaseEvent);
		this.upEventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnUpEventboxButtonPressEvent);
		this.upEventbox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnUpEventboxButtonReleaseEvent);
		this.leftEventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnLeftEventboxButtonPressEvent);
		this.leftEventbox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnLeftEventboxButtonReleaseEvent);
		this.enterEventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnEnterEventboxButtonPressEvent);
		this.enterEventbox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnEnterEventboxButtonReleaseEvent);
		this.rightEventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnRightEventboxButtonPressEvent);
		this.rightEventbox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnRightEventboxButtonReleaseEvent);
		this.downEventbox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDownEventboxButtonPressEvent);
		this.downEventbox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDownEventboxButtonReleaseEvent);
	}
}
