// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoBrickWebServer {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager ScriptManager;
		
		protected System.Web.UI.Timer UpdateTimer;
		
		protected System.Web.UI.UpdatePanel Sensor1TypePanel;
		
		protected System.Web.UI.WebControls.Label Sensor1TypeText;
		
		protected System.Web.UI.UpdatePanel Sensor1ModePanel;
		
		protected System.Web.UI.WebControls.Label Sensor1ModeText;
		
		protected System.Web.UI.UpdatePanel Sensor1PrevPanel;
		
		protected System.Web.UI.WebControls.Button sensor1Prev;
		
		protected System.Web.UI.UpdatePanel Sensor1NextPanel;
		
		protected System.Web.UI.WebControls.Button sensor1Next;
		
		protected System.Web.UI.UpdatePanel Sensor1ValuePanel;
		
		protected System.Web.UI.WebControls.Label Sensor1ValueText;
		
		protected System.Web.UI.UpdatePanel Sensor2TypePanel;
		
		protected System.Web.UI.WebControls.Label Sensor2TypeText;
		
		protected System.Web.UI.UpdatePanel Sensor2ModePanel;
		
		protected System.Web.UI.WebControls.Label Sensor2ModeText;
		
		protected System.Web.UI.UpdatePanel Sensor2PrevPanel;
		
		protected System.Web.UI.WebControls.Button sensor2Prev;
		
		protected System.Web.UI.UpdatePanel Sensor2NextPanel;
		
		protected System.Web.UI.WebControls.Button sensor2Next;
		
		protected System.Web.UI.UpdatePanel Sensor2ValuePanel;
		
		protected System.Web.UI.WebControls.Label Sensor2ValueText;
		
		protected System.Web.UI.UpdatePanel Sensor3TypePannel;
		
		protected System.Web.UI.WebControls.Label Sensor3TypeText;
		
		protected System.Web.UI.UpdatePanel Sensor3ModePanel;
		
		protected System.Web.UI.WebControls.Label Sensor3ModeText;
		
		protected System.Web.UI.UpdatePanel Sensor3PrevPanel;
		
		protected System.Web.UI.WebControls.Button sensor3Prev;
		
		protected System.Web.UI.UpdatePanel Sensor3NextPanel;
		
		protected System.Web.UI.WebControls.Button sensor3Next;
		
		protected System.Web.UI.UpdatePanel Sensor3ValuePannel;
		
		protected System.Web.UI.WebControls.Label Sensor3ValueText;
		
		protected System.Web.UI.UpdatePanel Sensor4TypePanel;
		
		protected System.Web.UI.WebControls.Label Sensor4TypeText;
		
		protected System.Web.UI.UpdatePanel Sensor4ModePanel;
		
		protected System.Web.UI.WebControls.Label Sensor4ModeText;
		
		protected System.Web.UI.UpdatePanel Sensor4PrevPanel;
		
		protected System.Web.UI.WebControls.Button sensor4Prev;
		
		protected System.Web.UI.UpdatePanel Sensor4NextPanel;
		
		protected System.Web.UI.WebControls.Button sensor4Next;
		
		protected System.Web.UI.UpdatePanel Sensor4VAluePanel;
		
		protected System.Web.UI.WebControls.Label Sensor4ValueText;
		
		protected System.Web.UI.UpdatePanel Motor1RevPanel;
		
		protected System.Web.UI.WebControls.Button Motor1Rev;
		
		protected System.Web.UI.UpdatePanel Motor1FwdPanel;
		
		protected System.Web.UI.WebControls.Button Motor1Fwd;
		
		protected System.Web.UI.UpdatePanel Motor1OffPanel;
		
		protected System.Web.UI.WebControls.Button Motor1Off;
		
		protected System.Web.UI.UpdatePanel Motor1BreakPanel;
		
		protected System.Web.UI.WebControls.Button Motor1BreakPrev;
		
		protected System.Web.UI.UpdatePanel Motor1MovePanel;
		
		protected System.Web.UI.WebControls.Button Motor1MoveTo;
		
		protected System.Web.UI.UpdatePanel Motor1PositionPanel;
		
		protected System.Web.UI.WebControls.TextBox Motor1PositionText;
		
		protected System.Web.UI.UpdatePanel Motor1TachoPanel;
		
		protected System.Web.UI.WebControls.Label Motor1TachoText;
		
		protected System.Web.UI.UpdatePanel Motor1ResetPanel;
		
		protected System.Web.UI.WebControls.Button Motor1Reset;
		
		protected System.Web.UI.UpdatePanel Motor2RevPanel;
		
		protected System.Web.UI.WebControls.Button Motor2Rev;
		
		protected System.Web.UI.UpdatePanel Motor2FwdPanel;
		
		protected System.Web.UI.WebControls.Button Motor2Fwd;
		
		protected System.Web.UI.UpdatePanel Motor2OffPanel;
		
		protected System.Web.UI.WebControls.Button Motor2Off;
		
		protected System.Web.UI.UpdatePanel Motor2BreakPanel;
		
		protected System.Web.UI.WebControls.Button Motor2BreakPrev;
		
		protected System.Web.UI.UpdatePanel Motor2MovePanel;
		
		protected System.Web.UI.WebControls.Button Motor2MoveTo;
		
		protected System.Web.UI.UpdatePanel Motor2PositionPanel;
		
		protected System.Web.UI.WebControls.TextBox Motor2PositionText;
		
		protected System.Web.UI.UpdatePanel Motor2TachoPanel;
		
		protected System.Web.UI.WebControls.Label Motor2TachoText;
		
		protected System.Web.UI.UpdatePanel Motor2ResetPanel;
		
		protected System.Web.UI.WebControls.Button Motor2Reset;
		
		protected System.Web.UI.UpdatePanel Motor3RevPanel;
		
		protected System.Web.UI.WebControls.Button Motor3Rev;
		
		protected System.Web.UI.UpdatePanel Motor3FwdPanel;
		
		protected System.Web.UI.WebControls.Button Motor3Fwd;
		
		protected System.Web.UI.UpdatePanel Motor3OffPanel;
		
		protected System.Web.UI.WebControls.Button Motor3Off;
		
		protected System.Web.UI.UpdatePanel Motor3BreakPanel;
		
		protected System.Web.UI.WebControls.Button Motor3BreakPrev;
		
		protected System.Web.UI.UpdatePanel Motor3MovePanel;
		
		protected System.Web.UI.WebControls.Button Motor3MoveTo;
		
		protected System.Web.UI.UpdatePanel Motor3PositionPanel;
		
		protected System.Web.UI.WebControls.TextBox Motor3PositionText;
		
		protected System.Web.UI.UpdatePanel Motor3TachoPanel;
		
		protected System.Web.UI.WebControls.Label Motor3TachoText;
		
		protected System.Web.UI.UpdatePanel Motor3ResetPanel;
		
		protected System.Web.UI.WebControls.Button Motor3Reset;
		
		protected System.Web.UI.UpdatePanel Motor4RevPanel;
		
		protected System.Web.UI.WebControls.Button Motor4Rev;
		
		protected System.Web.UI.UpdatePanel Motor4FwdPanel;
		
		protected System.Web.UI.WebControls.Button Motor4Fwd;
		
		protected System.Web.UI.UpdatePanel Motor4OffPanel;
		
		protected System.Web.UI.WebControls.Button Motor4Off;
		
		protected System.Web.UI.UpdatePanel Motor4BreakPanel;
		
		protected System.Web.UI.WebControls.Button Motor4BreakPrev;
		
		protected System.Web.UI.UpdatePanel Motor4MovePanel;
		
		protected System.Web.UI.WebControls.Button Motor4MoveTo;
		
		protected System.Web.UI.UpdatePanel Motor4PositionPanel;
		
		protected System.Web.UI.WebControls.TextBox Motor4PositionText;
		
		protected System.Web.UI.UpdatePanel Motor4TachoPanel;
		
		protected System.Web.UI.WebControls.Label Motor4TachoText;
		
		protected System.Web.UI.UpdatePanel Motor4ResetPanel;
		
		protected System.Web.UI.WebControls.Button Motor4Reset;
	}
}
