
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Fixed fixed10;
	
	private global::Gtk.Fixed fixed7;
	
	private global::Gtk.Fixed fixed8;
	
	private global::Gtk.Fixed fixed9;
	
	private global::Gtk.DrawingArea lcdDrawingarea;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.Button downButton;
	
	private global::Gtk.Button enterButton;
	
	private global::Gtk.Button escButton;
	
	private global::Gtk.Fixed fixed11;
	
	private global::Gtk.Fixed fixed12;
	
	private global::Gtk.Fixed fixed14;
	
	private global::Gtk.Button leftButton;
	
	private global::Gtk.Button rightButton;
	
	private global::Gtk.Button upButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.fixed10 = new global::Gtk.Fixed ();
		this.fixed10.Name = "fixed10";
		this.fixed10.HasWindow = false;
		this.table1.Add (this.fixed10);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed10]));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.table1.Add (this.fixed7);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed7]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed8 = new global::Gtk.Fixed ();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		this.table1.Add (this.fixed8);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed8]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed9 = new global::Gtk.Fixed ();
		this.fixed9.Name = "fixed9";
		this.fixed9.HasWindow = false;
		this.table1.Add (this.fixed9);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed9]));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.lcdDrawingarea = new global::Gtk.DrawingArea ();
		this.lcdDrawingarea.WidthRequest = 178;
		this.lcdDrawingarea.HeightRequest = 128;
		this.lcdDrawingarea.Name = "lcdDrawingarea";
		this.table1.Add (this.lcdDrawingarea);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.lcdDrawingarea]));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.downButton = new global::Gtk.Button ();
		this.downButton.CanFocus = true;
		this.downButton.Name = "downButton";
		this.downButton.UseUnderline = true;
		this.downButton.Label = global::Mono.Unix.Catalog.GetString ("_DOWN");
		this.table2.Add (this.downButton);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.downButton]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.enterButton = new global::Gtk.Button ();
		this.enterButton.CanFocus = true;
		this.enterButton.Name = "enterButton";
		this.enterButton.UseUnderline = true;
		this.enterButton.Label = global::Mono.Unix.Catalog.GetString ("OK");
		this.table2.Add (this.enterButton);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.enterButton]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.escButton = new global::Gtk.Button ();
		this.escButton.CanFocus = true;
		this.escButton.Name = "escButton";
		this.escButton.UseUnderline = true;
		this.escButton.Label = global::Mono.Unix.Catalog.GetString ("Esc");
		this.table2.Add (this.escButton);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.escButton]));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed11 = new global::Gtk.Fixed ();
		this.fixed11.Name = "fixed11";
		this.fixed11.HasWindow = false;
		this.table2.Add (this.fixed11);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed11]));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed12 = new global::Gtk.Fixed ();
		this.fixed12.Name = "fixed12";
		this.fixed12.HasWindow = false;
		this.table2.Add (this.fixed12);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed12]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed14 = new global::Gtk.Fixed ();
		this.fixed14.Name = "fixed14";
		this.fixed14.HasWindow = false;
		this.table2.Add (this.fixed14);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed14]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.leftButton = new global::Gtk.Button ();
		this.leftButton.CanFocus = true;
		this.leftButton.Name = "leftButton";
		this.leftButton.UseUnderline = true;
		this.leftButton.Label = global::Mono.Unix.Catalog.GetString ("LEFT");
		this.table2.Add (this.leftButton);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.leftButton]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.rightButton = new global::Gtk.Button ();
		this.rightButton.CanFocus = true;
		this.rightButton.Name = "rightButton";
		this.rightButton.UseUnderline = true;
		this.rightButton.Label = global::Mono.Unix.Catalog.GetString ("RIGHT");
		this.table2.Add (this.rightButton);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.rightButton]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.LeftAttach = ((uint)(2));
		w13.RightAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.upButton = new global::Gtk.Button ();
		this.upButton.CanFocus = true;
		this.upButton.Name = "upButton";
		this.upButton.UseUnderline = true;
		this.upButton.Label = global::Mono.Unix.Catalog.GetString ("_UP");
		this.table2.Add (this.upButton);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.upButton]));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add (this.table2);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.table2]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox3.Add (this.vbox1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox1]));
		w17.Position = 0;
		this.Add (this.hbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 236;
		this.DefaultHeight = 330;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.upButton.Pressed += new global::System.EventHandler (this.OnUpButtonPressed);
		this.upButton.Released += new global::System.EventHandler (this.OnUpButtonReleased);
		this.rightButton.Pressed += new global::System.EventHandler (this.OnRightButtonPressed);
		this.rightButton.Released += new global::System.EventHandler (this.OnRightButtonReleased);
		this.leftButton.Pressed += new global::System.EventHandler (this.OnLeftButtonPressed);
		this.leftButton.Released += new global::System.EventHandler (this.OnLeftButtonReleased);
		this.escButton.Pressed += new global::System.EventHandler (this.OnEscButtonPressed);
		this.escButton.Released += new global::System.EventHandler (this.OnEscButtonReleased);
		this.enterButton.Pressed += new global::System.EventHandler (this.OnEnterButtonPressed);
		this.enterButton.Released += new global::System.EventHandler (this.OnEnterButtonReleased);
		this.downButton.Pressed += new global::System.EventHandler (this.OnDownButtonPressed);
		this.downButton.Released += new global::System.EventHandler (this.OnDownButtonReleased);
	}
}
